server {
    listen 80;
    server_name _;
    access_log /var/log/nginx/mywebapp_access.log;

    location = / {
        proxy_pass http://127.0.0.1:8000;
    }

    location /tasks {
        proxy_pass http://127.0.0.1:8000;
    }

    location / {
        return 404;
    }
}